/* global console, process */

import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";

const packageDirectory = dirname(dirname(fileURLToPath(import.meta.url)));
const checkOnly = process.argv.includes("--check");
const lockPath = join(packageDirectory, "icons.lock.json");
const generatedSourcePath = join(packageDirectory, "src/icons.ts");
const generatedManifestPath = join(packageDirectory, "src/icons.manifest.json");
const prettierOptions = { printWidth: 100, semi: true, singleQuote: false, trailingComma: "none" };
const allowedTags = new Set(["circle", "ellipse", "line", "path", "polygon", "polyline", "rect"]);
const allowedAttributes = new Set([
  "clip-rule",
  "cx",
  "cy",
  "d",
  "fill-rule",
  "height",
  "opacity",
  "points",
  "r",
  "rx",
  "ry",
  "width",
  "x",
  "x1",
  "x2",
  "y",
  "y1",
  "y2"
]);

function sha256(value) {
  return createHash("sha256").update(value).digest("hex");
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function parseAttributes(source, iconId) {
  const attributes = {};
  const residue = source.replace(/([a-zA-Z][\w:-]*)="([^"]*)"/g, (_, name, value) => {
    assert(allowedAttributes.has(name), `${iconId}: unsupported SVG attribute ${name}`);
    attributes[name] = value;
    return "";
  });
  assert(residue.trim() === "", `${iconId}: could not parse all SVG attributes`);
  return attributes;
}

function parseIcon(svg, iconId) {
  assert(svg.includes('viewBox="0 0 24 24"'), `${iconId}: expected a 24 x 24 viewBox`);
  assert(svg.includes('fill="none"'), `${iconId}: expected fill=none`);
  assert(svg.includes('stroke="currentColor"'), `${iconId}: expected currentColor stroke`);
  assert(svg.includes('stroke-linecap="round"'), `${iconId}: expected round line caps`);
  assert(svg.includes('stroke-linejoin="round"'), `${iconId}: expected round line joins`);

  const svgBody = svg.match(/<svg\b[^>]*>([\s\S]*?)<\/svg>/)?.[1];
  assert(svgBody !== undefined, `${iconId}: could not find the SVG body`);
  const nodes = [];
  const childPattern = /<([a-z][a-z0-9-]*)\s+([^<>]*?)\s*\/>/g;
  const residue = svgBody.replace(childPattern, (_, tag, attributes) => {
    assert(allowedTags.has(tag), `${iconId}: unsupported SVG element ${tag}`);
    nodes.push([tag, parseAttributes(attributes, iconId)]);
    return "";
  });
  assert(residue.trim() === "", `${iconId}: SVG contains unsupported child content`);
  assert(nodes.length > 0, `${iconId}: SVG contains no geometry`);
  return nodes;
}

function formatObject(value) {
  return `{ ${Object.entries(value)
    .map(([key, attributeValue]) => {
      const formattedKey = /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
      return `${formattedKey}: ${JSON.stringify(attributeValue)}`;
    })
    .join(", ")} }`;
}

function formatPropertyKey(key) {
  return /^[A-Za-z_$][\w$]*$/.test(key) ? key : JSON.stringify(key);
}

function formatNodes(nodes) {
  if (nodes.length === 1) {
    const [tag, attributes] = nodes[0];
    return `[[${JSON.stringify(tag)}, ${formatObject(attributes)}]]`;
  }
  return `[\n${nodes
    .map(([tag, attributes]) => `  [${JSON.stringify(tag)}, ${formatObject(attributes)}]`)
    .join(",\n")}\n]`;
}

function generateSource(icons) {
  const declarations = icons
    .map(
      ({ coreExport, id, nodes, upstream }) => `/**
 * Geometry for Meu ID \`${id}\`, generated unchanged from Lucide \`${upstream}\`.
 *
 * @public
 */
export const ${coreExport} = ${formatNodes(nodes)} as const;`
    )
    .join("\n\n");
  const registry = icons
    .map(({ coreExport, id }) => `  ${formatPropertyKey(id)}: ${coreExport}`)
    .join(",\n");

  return `// Generated by scripts/generate-icons.mjs from icons.lock.json. Do not edit directly.

/**
 * SVG attributes stored by the platform-neutral Meu icon registry.
 *
 * @public
 */
export type MeuIconNodeAttributes = Readonly<Record<string, string>>;

/**
 * A read-only list of SVG element names and attributes using the shared 24 × 24 viewBox.
 *
 * @public
 */
export type MeuIconNode = ReadonlyArray<readonly [tag: string, attributes: MeuIconNodeAttributes]>;

${declarations}

/**
 * The curated registry, keyed by stable Meu IDs and generated from traced Lucide sources.
 *
 * @public
 */
export const meuIconNodes = {
${registry}
} as const satisfies Record<string, MeuIconNode>;

/**
 * Stable semantic IDs accepted by the Meu icon registry.
 *
 * @public
 */
export type MeuIconName = keyof typeof meuIconNodes;
`;
}

async function readLock() {
  const lock = JSON.parse(await readFile(lockPath, "utf8"));
  assert(lock.schemaVersion === 1, "Unsupported icon lock schema");
  assert(Array.isArray(lock.icons) && lock.icons.length > 0, "Icon lock must contain icons");
  assert(
    new Set(lock.icons.map((icon) => icon.id)).size === lock.icons.length,
    "Duplicate Meu icon ID"
  );
  assert(
    new Set(lock.icons.map((icon) => icon.coreExport)).size === lock.icons.length,
    "Duplicate core icon export"
  );
  return lock;
}

async function loadIcons(lock) {
  const license = await readFile(join(packageDirectory, lock.upstream.licenseFile));
  assert(
    sha256(license) === lock.upstream.licenseSha256,
    `${lock.upstream.licenseFile}: license checksum mismatch`
  );
  const featherLicense = await readFile(join(packageDirectory, lock.upstream.featherLicenseFile));
  assert(
    sha256(featherLicense) === lock.upstream.featherLicenseSha256,
    `${lock.upstream.featherLicenseFile}: license checksum mismatch`
  );

  return Promise.all(
    lock.icons.map(async (icon) => {
      assert(
        icon.modified === false,
        `${icon.id}: modified geometry requires a separate review path`
      );
      const source = await readFile(join(packageDirectory, icon.source));
      assert(sha256(source) === icon.sourceSha256, `${icon.id}: upstream SVG checksum mismatch`);
      const nodes = parseIcon(source.toString("utf8"), icon.id);
      return { ...icon, geometrySha256: sha256(JSON.stringify(nodes)), nodes };
    })
  );
}

function generateManifest(lock, icons) {
  const commitUrl = `${lock.upstream.repository}/tree/${lock.upstream.gitCommit}`;
  return {
    schemaVersion: 1,
    generatedBy: "packages/icons-core/scripts/generate-icons.mjs",
    upstream: {
      name: lock.upstream.name,
      package: lock.upstream.package,
      version: lock.upstream.version,
      license: lock.upstream.license,
      licenseFile: lock.upstream.licenseFile,
      repository: lock.upstream.repository,
      gitTag: lock.upstream.gitTag,
      gitCommit: lock.upstream.gitCommit,
      commitUrl,
      archiveUrl: lock.upstream.archiveUrl,
      archiveIntegrity: lock.upstream.archiveIntegrity
    },
    provenanceAudit: {
      status: "verified",
      reviewed: lock.reviewed,
      verified: [
        "Every exported Meu icon ID maps to a named Lucide source and React export.",
        "The generator verifies the checked-in upstream SVG and license SHA-256 checksums.",
        "The optional network audit verifies the fixed npm archive SHA-512 before comparing files.",
        "Generated TypeScript and this manifest are covered by the offline drift check."
      ],
      legalReviewRequired:
        "Engineering verified source identity and reproduced upstream notices; counsel must approve commercial distribution obligations."
    },
    icons: icons.map(
      ({
        geometrySha256,
        id,
        licenseFiles,
        licenses,
        modified,
        reactExport,
        source,
        sourceSha256,
        upstream
      }) => ({
        id,
        upstream,
        upstreamUrl: `${lock.upstream.repository}/blob/${lock.upstream.gitCommit}/icons/${upstream}.svg`,
        react: reactExport,
        source,
        sourceSha256,
        geometrySha256,
        modified,
        licenses,
        licenseFiles
      })
    )
  };
}

async function writeOrCheck(path, expected) {
  if (!checkOnly) {
    await writeFile(path, expected);
    return;
  }
  const actual = await readFile(path, "utf8");
  assert(
    actual === expected,
    `${path}: generated output drifted; run pnpm --filter @meu/icons-core icons:generate`
  );
}

const lock = await readLock();
const icons = await loadIcons(lock);
await writeOrCheck(
  generatedSourcePath,
  await format(generateSource(icons), { ...prettierOptions, parser: "typescript" })
);
await writeOrCheck(
  generatedManifestPath,
  await format(JSON.stringify(generateManifest(lock, icons)), {
    ...prettierOptions,
    parser: "json"
  })
);
console.log(
  checkOnly ? "Icon provenance and generated files are current." : "Generated icon files."
);
