// Generated by scripts/generate-icons.mjs from icons.lock.json. Do not edit directly.

/**
 * SVG attributes stored by the platform-neutral Meu icon registry.
 *
 * @public
 */
export type MeuIconNodeAttributes = Readonly<Record<string, string>>;

/**
 * A read-only list of SVG element names and attributes using the shared 24 × 24 viewBox.
 *
 * @public
 */
export type MeuIconNode = ReadonlyArray<readonly [tag: string, attributes: MeuIconNodeAttributes]>;

/**
 * Geometry for Meu ID `chevron-left`, generated unchanged from Lucide `chevron-left`.
 *
 * @public
 */
export const meuIconChevronLeft = [["path", { d: "m15 18-6-6 6-6" }]] as const;

/**
 * Geometry for Meu ID `check`, generated unchanged from Lucide `check`.
 *
 * @public
 */
export const meuIconCheck = [["path", { d: "M20 6 9 17l-5-5" }]] as const;

/**
 * Geometry for Meu ID `plus`, generated unchanged from Lucide `plus`.
 *
 * @public
 */
export const meuIconPlus = [
  ["path", { d: "M5 12h14" }],
  ["path", { d: "M12 5v14" }]
] as const;

/**
 * Geometry for Meu ID `search`, generated unchanged from Lucide `search`.
 *
 * @public
 */
export const meuIconSearch = [
  ["path", { d: "m21 21-4.34-4.34" }],
  ["circle", { cx: "11", cy: "11", r: "8" }]
] as const;

/**
 * Geometry for Meu ID `x`, generated unchanged from Lucide `x`.
 *
 * @public
 */
export const meuIconX = [
  ["path", { d: "M18 6 6 18" }],
  ["path", { d: "m6 6 12 12" }]
] as const;

/**
 * The curated registry, keyed by stable Meu IDs and generated from traced Lucide sources.
 *
 * @public
 */
export const meuIconNodes = {
  "chevron-left": meuIconChevronLeft,
  check: meuIconCheck,
  plus: meuIconPlus,
  search: meuIconSearch,
  x: meuIconX
} as const satisfies Record<string, MeuIconNode>;

/**
 * Stable semantic IDs accepted by the Meu icon registry.
 *
 * @public
 */
export type MeuIconName = keyof typeof meuIconNodes;
